require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');
const db = require('../config/db');

const products = [
  {
    name: 'Wireless Headphones',
    description: 'High quality wireless headphones with noise cancellation.',
    price: 99.99,
    category: 'Electronics',
    brand: 'SoundMax',
    sku: 'SM-H100',
    stock: 50,
    weight: '250g',
    dimensions: '18x15x7cm',
    warranty: '2 years',
    origin: 'China',
    shipping: 'Free',
    returns: '30 days',
    image: 'headphones.jpg'
  },
  {
    name: 'Smart Watch',
    description: 'Feature-rich smart watch with health tracking.',
    price: 149.99,
    category: 'Electronics',
    brand: 'TechTime',
    sku: 'TT-SW200',
    stock: 40,
    weight: '60g',
    dimensions: '4x4x1cm',
    warranty: '1 year',
    origin: 'Japan',
    shipping: 'Free',
    returns: '30 days',
    image: 'smartwatch.jpg'
  },
  {
    name: 'Bluetooth Speaker',
    description: 'Portable Bluetooth speaker with deep bass.',
    price: 59.99,
    category: 'Electronics',
    brand: 'BassPro',
    sku: 'BP-BS300',
    stock: 60,
    weight: '500g',
    dimensions: '20x8x8cm',
    warranty: '1 year',
    origin: 'USA',
    shipping: 'Free',
    returns: '30 days',
    image: 'speaker.jpg'
  },
  {
    name: 'Gaming Mouse',
    description: 'Ergonomic gaming mouse with customizable buttons.',
    price: 39.99,
    category: 'Electronics',
    brand: 'GamePro',
    sku: 'GP-M500',
    stock: 70,
    weight: '120g',
    dimensions: '12x7x4cm',
    warranty: '2 years',
    origin: 'Germany',
    shipping: 'Free',
    returns: '30 days',
    image: 'mouse.jpg'
  },
  {
    name: 'Yoga Mat',
    description: 'Non-slip yoga mat for all types of exercises.',
    price: 29.99,
    category: 'Fitness',
    brand: 'FlexFit',
    sku: 'FF-YM100',
    stock: 80,
    weight: '900g',
    dimensions: '180x60x0.5cm',
    warranty: '6 months',
    origin: 'India',
    shipping: 'Free',
    returns: '30 days',
    image: 'yogamat.jpg'
  },
  {
    name: 'Running Shoes',
    description: 'Lightweight running shoes for men and women.',
    price: 89.99,
    category: 'Fitness',
    brand: 'RunFast',
    sku: 'RF-RS200',
    stock: 35,
    weight: '600g',
    dimensions: '30x20x12cm',
    warranty: '1 year',
    origin: 'Vietnam',
    shipping: 'Free',
    returns: '30 days',
    image: 'shoes.jpg'
  },
  {
    name: 'Water Bottle',
    description: 'Insulated water bottle keeps drinks cold for 24 hours.',
    price: 19.99,
    category: 'Fitness',
    brand: 'HydroMax',
    sku: 'HM-WB300',
    stock: 100,
    weight: '350g',
    dimensions: '25x7x7cm',
    warranty: '1 year',
    origin: 'USA',
    shipping: 'Free',
    returns: '30 days',
    image: 'bottle.jpg'
  },
  {
    name: 'Backpack',
    description: 'Durable backpack for travel and daily use.',
    price: 49.99,
    category: 'Accessories',
    brand: 'PackPro',
    sku: 'PP-BP400',
    stock: 45,
    weight: '700g',
    dimensions: '45x30x15cm',
    warranty: '2 years',
    origin: 'Bangladesh',
    shipping: 'Free',
    returns: '30 days',
    image: 'backpack.jpg'
  },
  {
    name: 'Sunglasses',
    description: 'UV-protected stylish sunglasses.',
    price: 24.99,
    category: 'Accessories',
    brand: 'SunGuard',
    sku: 'SG-SG500',
    stock: 55,
    weight: '80g',
    dimensions: '15x5x4cm',
    warranty: '1 year',
    origin: 'Italy',
    shipping: 'Free',
    returns: '30 days',
    image: 'sunglasses.jpg'
  },
  {
    name: 'Leather Wallet',
    description: 'Premium leather wallet with multiple compartments.',
    price: 34.99,
    category: 'Accessories',
    brand: 'WalletPro',
    sku: 'WP-LW600',
    stock: 65,
    weight: '150g',
    dimensions: '12x9x2cm',
    warranty: '1 year',
    origin: 'Turkey',
    shipping: 'Free',
    returns: '30 days',
    image: 'wallet.jpg'
  },
  {
    name: 'Desk Lamp',
    description: 'LED desk lamp with adjustable brightness.',
    price: 27.99,
    category: 'Home',
    brand: 'BrightLite',
    sku: 'BL-DL700',
    stock: 75,
    weight: '400g',
    dimensions: '35x12x12cm',
    warranty: '2 years',
    origin: 'China',
    shipping: 'Free',
    returns: '30 days',
    image: 'lamp.jpg'
  },
  {
    name: 'Coffee Maker',
    description: 'Automatic coffee maker with timer.',
    price: 79.99,
    category: 'Home',
    brand: 'BrewMaster',
    sku: 'BM-CM800',
    stock: 30,
    weight: '2kg',
    dimensions: '30x25x20cm',
    warranty: '2 years',
    origin: 'Brazil',
    shipping: 'Free',
    returns: '30 days',
    image: 'coffeemaker.jpg'
  },
  {
    name: 'Throw Blanket',
    description: 'Soft and cozy throw blanket for your couch.',
    price: 22.99,
    category: 'Home',
    brand: 'CozyHome',
    sku: 'CH-TB900',
    stock: 90,
    weight: '800g',
    dimensions: '150x120cm',
    warranty: '1 year',
    origin: 'India',
    shipping: 'Free',
    returns: '30 days',
    image: 'blanket.jpg'
  },
  {
    name: 'Cookware Set',
    description: 'Non-stick cookware set for all your kitchen needs.',
    price: 129.99,
    category: 'Home',
    brand: 'ChefPro',
    sku: 'CP-CS1000',
    stock: 25,
    weight: '3kg',
    dimensions: '50x30x20cm',
    warranty: '5 years',
    origin: 'France',
    shipping: 'Free',
    returns: '30 days',
    image: 'cookware.jpg'
  },
  {
    name: 'T-shirt',
    description: '100% cotton t-shirt available in multiple colors.',
    price: 14.99,
    category: 'Clothing',
    brand: 'CottonWear',
    sku: 'CW-TS1100',
    stock: 120,
    weight: '200g',
    dimensions: 'L/XL',
    warranty: '1 year',
    origin: 'Bangladesh',
    shipping: 'Free',
    returns: '30 days',
    image: 'tshirt.jpg'
  },
  {
    name: 'Jeans',
    description: 'Classic fit jeans for everyday wear.',
    price: 49.99,
    category: 'Clothing',
    brand: 'DenimPro',
    sku: 'DP-J1200',
    stock: 60,
    weight: '600g',
    dimensions: '32/34',
    warranty: '2 years',
    origin: 'Mexico',
    shipping: 'Free',
    returns: '30 days',
    image: 'jeans.jpg'
  },
  {
    name: 'Jacket',
    description: 'Water-resistant jacket for all seasons.',
    price: 89.99,
    category: 'Clothing',
    brand: 'WeatherGuard',
    sku: 'WG-J1300',
    stock: 40,
    weight: '900g',
    dimensions: 'L/XL',
    warranty: '3 years',
    origin: 'Canada',
    shipping: 'Free',
    returns: '30 days',
    image: 'jacket.jpg'
  },
  {
    name: 'Sneakers',
    description: 'Comfortable sneakers for casual outings.',
    price: 59.99,
    category: 'Clothing',
    brand: 'StepPro',
    sku: 'SP-S1400',
    stock: 80,
    weight: '700g',
    dimensions: '42/44',
    warranty: '1 year',
    origin: 'Vietnam',
    shipping: 'Free',
    returns: '30 days',
    image: 'sneakers.jpg'
  },
  {
    name: 'Dress',
    description: 'Elegant dress for special occasions.',
    price: 69.99,
    category: 'Clothing',
    brand: 'ElegantWear',
    sku: 'EW-D1500',
    stock: 30,
    weight: '400g',
    dimensions: 'M/L',
    warranty: '1 year',
    origin: 'Italy',
    shipping: 'Free',
    returns: '30 days',
    image: 'dress.jpg'
  },
  {
    name: 'Cap',
    description: 'Adjustable baseball cap.',
    price: 12.99,
    category: 'Clothing',
    brand: 'CapKing',
    sku: 'CK-C1600',
    stock: 100,
    weight: '100g',
    dimensions: 'One Size',
    warranty: '6 months',
    origin: 'China',
    shipping: 'Free',
    returns: '30 days',
    image: 'cap.jpg'
  }
];

async function seedProducts() {
  try {
    await db();
    await Product.deleteMany();
    await Product.insertMany(products);
    console.log('20 products seeded successfully');
    process.exit();
  } catch (error) {
    console.error('Error seeding products:', error);
    process.exit(1);
  }
}

seedProducts();
